### ISSUE TITLE
Move to SQL

### ISSUE THREAD

**Issue by ghost** [mikaelssen/Jefmajor.com#1]
I need advice on this, not sure how to hide the credentials for the DB if i open source it. 
How would i proceed to implement this?...
Would pretty much just move the Quote Flat-file database to MySQL and then fetch every quote or latest 30 quotes/similar upon page creation, and have a dynamic loading page when scrolling down, just so the future won't load 200k quotes.

**Comment by NaakkaDev** [comment]
If you're sure that you want to use MySQL for quotes, then you can just create a **config.sample.php** with example values and put **config.php** in **.gitignore** so the real config file (rename config.sample.php to config.php and add correct db credentials) with DB credentials is not added to the repo.

In my opinion there would be better options than MySQL for quotes though, JSON file-based database or something like that, https://www.rethinkdb.com/ could work well for example.

**Comment by ghost** [comment]
Will have to look into that, Alternatives are always welcome!

**Comment by knyghty** [comment]
I'd probably only bother moving to a sql database if you wanted to use it for more than just quotes.

Anyway the best way to store configuration is probably in the environment. I don't use php anymore because it's awful but you should be able to get environment variables and use those values. Then just set them on the server however you want. Trying to mess around with files not checked into version control gets messy.

**Comment by ghost** [comment]
Probably, But i think flat-files will do just fine for now, it's more of a future problem if anyone should require it, but until then we'll just use rethink or something similar. But as of now it's a non issue and i think i'll just close it off :)

Also i have nothing against moving away from php, but i'm not what one would replace it with effectively.
